name: Nimble Security Audit

on:
  push
  #schedule:
  #  - cron: "0 0 * * *"

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-python@v1

    - name: Update Python PIP
      run: pip install --upgrade --disable-pip-version-check pip python-ptrace==0.9.1

    - name: Cache choosenim
      id: cache-choosenim
      uses: actions/cache@v1
      with:
        path: ~/.choosenim
        key: ${{ runner.os }}-choosenim-$CHOOSENIM_CHOOSE_VERSION

    - uses: jiro4989/setup-nim-action@v1.0.2
      with:
        nim-version: "stable"

    - name: Nimble Refresh
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nimble -y refresh

    - name: Compile
      run: |
        export PATH=$HOME/.nimble/bin:$PATH
        nim c --panics:on nimble_security_checker.nim

    - name: Run
      timeout-minutes: 360  # 360 max
      run: |
        export CHOOSENIM_NO_ANALYTICS=1
        export PATH=$HOME/.nimble/bin:$PATH
        ./nimble_security_checker

    - uses: stefanzweifel/git-auto-commit-action@v4.1.3
      with:
        commit_message: Fully Automated Luxury Security Audit
        file_pattern: "*.log"
        commit_user_name: juancarlospaco
        commit_author: Juan Carlos
        branch: master
        commit_options: "--no-verify"
